'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://module1.com/calculator", ConfigurationName:="ServiceReference1.CalculatorSoap")>  _
    Public Interface CalculatorSoap
        
        'CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento AddResult dallo spazio dei nomi http://module1.com/calculator non è contrassegnato come nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://module1.com/calculator/Add", ReplyAction:="*")>  _
        Function Add(ByVal request As ServiceReference1.AddRequest) As ServiceReference1.AddResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://module1.com/calculator/Add", ReplyAction:="*")>  _
        Function AddAsync(ByVal request As ServiceReference1.AddRequest) As System.Threading.Tasks.Task(Of ServiceReference1.AddResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Add", [Namespace]:="http://module1.com/calculator", Order:=0)>  _
        Public Body As ServiceReference1.AddRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.AddRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://module1.com/calculator")>  _
    Partial Public Class AddRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public a As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public b As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal a As Integer, ByVal b As Integer)
            MyBase.New
            Me.a = a
            Me.b = b
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddResponse", [Namespace]:="http://module1.com/calculator", Order:=0)>  _
        Public Body As ServiceReference1.AddResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.AddResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://module1.com/calculator")>  _
    Partial Public Class AddResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AddResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AddResult As String)
            MyBase.New
            Me.AddResult = AddResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CalculatorSoapChannel
        Inherits ServiceReference1.CalculatorSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CalculatorSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.CalculatorSoap)
        Implements ServiceReference1.CalculatorSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_CalculatorSoap_Add(ByVal request As ServiceReference1.AddRequest) As ServiceReference1.AddResponse Implements ServiceReference1.CalculatorSoap.Add
            Return MyBase.Channel.Add(request)
        End Function
        
        Public Function Add(ByVal a As Integer, ByVal b As Integer) As String
            Dim inValue As ServiceReference1.AddRequest = New ServiceReference1.AddRequest()
            inValue.Body = New ServiceReference1.AddRequestBody()
            inValue.Body.a = a
            inValue.Body.b = b
            Dim retVal As ServiceReference1.AddResponse = CType(Me,ServiceReference1.CalculatorSoap).Add(inValue)
            Return retVal.Body.AddResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_CalculatorSoap_AddAsync(ByVal request As ServiceReference1.AddRequest) As System.Threading.Tasks.Task(Of ServiceReference1.AddResponse) Implements ServiceReference1.CalculatorSoap.AddAsync
            Return MyBase.Channel.AddAsync(request)
        End Function
        
        Public Function AddAsync(ByVal a As Integer, ByVal b As Integer) As System.Threading.Tasks.Task(Of ServiceReference1.AddResponse)
            Dim inValue As ServiceReference1.AddRequest = New ServiceReference1.AddRequest()
            inValue.Body = New ServiceReference1.AddRequestBody()
            inValue.Body.a = a
            inValue.Body.b = b
            Return CType(Me,ServiceReference1.CalculatorSoap).AddAsync(inValue)
        End Function
    End Class
End Namespace
